"""Explicit loader for locally generated sklearn Peptide-OmniPanel bundles."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .panel import ModelBundle, ModelEntry, PredictionContext
from .training import feature_vector_for_sequence


@dataclass
class SklearnTaskPredictor:
    estimator: Any
    entry: ModelEntry

    def __call__(self, context: PredictionContext) -> dict[str, Any]:
        try:
            import numpy as np
        except ImportError as exc:  # pragma: no cover - deployment contract.
            raise RuntimeError("NumPy is required for sklearn inference") from exc
        matrix = np.asarray(
            [feature_vector_for_sequence(context.sequence)],
            dtype=np.float32,
        )
        if self.entry.task_kind == "binary_classification":
            probabilities = self.estimator.predict_proba(matrix)
            classes = list(self.estimator.classes_)
            probability = (
                float(probabilities[0, classes.index(1)]) if 1 in classes else 0.0
            )
            value = None
            interval = None
        elif self.entry.task_kind == "regression":
            value = float(self.estimator.predict(matrix)[0])
            probability = None
            width = self.entry.interval_half_width
            interval = None if width is None else [value - float(width), value + float(width)]
        else:
            raise ValueError("model entry is missing a supported task_kind")

        length = len(context.sequence)
        minimum = self.entry.sequence_length_min
        maximum = self.entry.sequence_length_max
        in_range = (minimum is None or length >= minimum) and (
            maximum is None or length <= maximum
        )
        support_is_primary = self.entry.support_tier == "primary"
        return {
            "value": value,
            "probability": probability,
            "prediction_interval": interval,
            "status": "predicted" if support_is_primary and in_range else "low_confidence",
            "applicability": "length_in_training_range" if in_range else "length_out_of_range",
            "reason": None if in_range else "sequence_length_outside_training_range",
        }


def load_model_bundle(manifest_path: str | Path) -> ModelBundle:
    """Load only artifacts rooted next to an explicit local manifest.

    Joblib deserialization can execute Python and is therefore intentionally not
    triggered by ``ModelBundle.from_manifest`` itself. This function is the
    deployment boundary and must only receive manifests generated by this project.
    """

    manifest = Path(manifest_path).resolve()
    root = manifest.parent.resolve()

    def loader(entry: ModelEntry) -> SklearnTaskPredictor | None:
        if entry.artifact_path is None:
            return None
        artifact = (root / entry.artifact_path).resolve()
        try:
            artifact.relative_to(root)
        except ValueError as exc:
            raise ValueError(f"model artifact escapes manifest directory: {artifact}") from exc
        try:
            import joblib
        except ImportError as exc:  # pragma: no cover - deployment contract.
            raise RuntimeError("joblib is required to load model artifacts") from exc
        payload = joblib.load(artifact)
        if not isinstance(payload, dict) or "model" not in payload:
            raise ValueError(f"invalid model bundle payload: {artifact}")
        return SklearnTaskPredictor(estimator=payload["model"], entry=entry)

    return ModelBundle.from_manifest(manifest, loader=loader)
